apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-backend
  namespace: apps
  labels:
    app: api-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-backend
  template:
    metadata:
      labels:
        app: api-backend
    spec:
      containers:
        - name: api-backend
          image: us-central1-docker.pkg.dev/app-dev-468521/apps/api-backend:9e5500f8e385c32bb36ec56ddf974a42e84b9c78
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: ALLOWED_ORIGIN
              value: "https://pueba-web-dev.com"   # your static site origin (Apigee will handle browser CORS)
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
