apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-backend
  namespace: apps
  annotations:
    kubernetes.io/ingress.class: "gce-internal"
spec:
  rules:
    - host: backend.internal
      http:
        paths:
          - path: /solutions
            pathType: Prefix
            backend:
              service:
                name: api-backend      # ClusterIP
                port:
                  number: 80
          - path: /delivery
            pathType: Prefix
            backend:
              service:
                name: api-backend
                port:
                  number: 80
          - path: /status
            pathType: Prefix
            backend:
              service:
                name: api-backend
                port:
                  number: 80
