apiVersion: v1
kind: Service
metadata:
  name: api-backend
  namespace: apps
  labels:
    app: api-backend
spec:
  type: ClusterIP
  selector:
    app: api-backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
